import random

quotes = [
    {"quote": "The best way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"quote": "Don't let yesterday take up too much of today.", "author": "Will Rogers"},
    {"quote": "It's not whether you get knocked down, it's whether you get up.", "author": "Vince Lombardi"},
    {"quote": "Success is not in what you have, but who you are.", "author": "Bo Bennett"},
        {"quote": "The best way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"quote": "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", "author": "Winston Churchill"},
    {"quote": "Don’t let yesterday take up too much of today.", "author": "Will Rogers"},
    {"quote": "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", "author": "Unknown"},
    {"quote": "It’s not whether you get knocked down, it’s whether you get up.", "author": "Vince Lombardi"},
    {"quote": "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", "author": "Steve Jobs"},
    {"quote": "People who are crazy enough to think they can change the world, are the ones who do.", "author": "Rob Siltanen"},
    {"quote": "Failure will never overtake me if my determination to succeed is strong enough.", "author": "Og Mandino"},
    {"quote": "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. That’s the classic entrepreneurial skill.", "author": "Mohnish Pabrai"},
    {"quote": "We may encounter many defeats but we must not be defeated.", "author": "Maya Angelou"},
    {"quote": "Knowing is not enough; we must apply. Wishing is not enough; we must do.", "author": "Johann Wolfgang von Goethe"},
    {"quote": "Imagine your life is perfect in every respect; what would it look like?", "author": "Brian Tracy"},
    {"quote": "We generate fears while we sit. We overcome them by action.", "author": "Dr. Henry Link"},
    {"quote": "Whether you think you can or you think you can’t, you’re right.", "author": "Henry Ford"},
    {"quote": "Security is mostly a superstition. Life is either a daring adventure or nothing.", "author": "Helen Keller"},
    {"quote": "The man who has confidence in himself gains the confidence of others.", "author": "Hasidic Proverb"},
    {"quote": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"quote": "Creativity is intelligence having fun.", "author": "Albert Einstein"},
    {"quote": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar"},
    {"quote": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky"},
    {"quote": "I am not a product of my circumstances. I am a product of my decisions.", "author": "Stephen Covey"},
    {"quote": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi"},
    {"quote": "Life isn’t about finding yourself. It’s about creating yourself.", "author": "George Bernard Shaw"},
    {"quote": "Don’t judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson"},
    {"quote": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt"},
    {"quote": "Tell me who admires and loves you, and I will tell you who you are.", "author": "Antoine de Saint-Exupery"},
    {"quote": "The best revenge is massive success.", "author": "Frank Sinatra"},
    {"quote": "Life is what happens when you’re busy making other plans.", "author": "John Lennon"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "In three words I can sum up everything I’ve learned about life: it goes on.", "author": "Robert Frost"},
    {"quote": "Love the life you live. Live the life you love.", "author": "Bob Marley"},
    {"quote": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"quote": "May you live all the days of your life.", "author": "Jonathan Swift"},
    {"quote": "Life itself is the most wonderful fairy tale.", "author": "Hans Christian Andersen"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller"},
    {"quote": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"quote": "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "author": "Unknown"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is what happens when you’re busy making other plans.", "author": "John Lennon"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "In three words I can sum up everything I’ve learned about life: it goes on.", "author": "Robert Frost"},
    {"quote": "Love the life you live. Live the life you love.", "author": "Bob Marley"},
    {"quote": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"quote": "May you live all the days of your life.", "author": "Jonathan Swift"},
    {"quote": "Life itself is the most wonderful fairy tale.", "author": "Hans Christian Andersen"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller"},
    {"quote": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"quote": "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "author": "Unknown"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is what happens when you’re busy making other plans.", "author": "John Lennon"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "In three words I can sum up everything I’ve learned about life: it goes on.", "author": "Robert Frost"},
    {"quote": "Love the life you live. Live the life you love.", "author": "Bob Marley"},
    {"quote": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"quote": "May you live all the days of your life.", "author": "Jonathan Swift"},
    {"quote": "Life itself is the most wonderful fairy tale.", "author": "Hans Christian Andersen"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller"},
    {"quote": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"quote": "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "author": "Unknown"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is what happens when you’re busy making other plans.", "author": "John Lennon"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "In three words I can sum up everything I’ve learned about life: it goes on.", "author": "Robert Frost"},
    {"quote": "Love the life you live. Live the life you love.", "author": "Bob Marley"},
    {"quote": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"quote": "May you live all the days of your life.", "author": "Jonathan Swift"},
    {"quote": "Life itself is the most wonderful fairy tale.", "author": "Hans Christian Andersen"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is either a daring adventure or nothing at all.", "author": "Helen Keller"},
    {"quote": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"quote": "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "author": "Unknown"},
    {"quote": "Good friends, good books, and a sleepy conscience: this is the ideal life.", "author": "Mark Twain"},
    {"quote": "Life is what happens when you’re busy making other plans.", "author": "John Lennon"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "In three words I can sum up everything I’ve learned about life: it goes on.", "author": "Robert Frost"},
    {"quote": "Love the life you live. Live the life you love.", "author": "Bob Marley"},
    {"quote": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"quote": "May you live all the days of your life.", "author": "Jonathan Swift"},
    {"quote": "Life itself is the most wonderful fairy tale.", "author": "Hans Christian Andersen"}
]

def get_random_quote():
    return random.choice(quotes)